### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Visne** [PlaceNL/Chief#15]
```
Jul 21 22:28:11 nas node[754314]: file:///home/place/src/Chief/src/place/PlaceClient.js:115
Jul 21 22:28:11 nas node[754314]:         const configRaw = body.split('<script id="data">window.___r = ')[1].split(';</script>')[0];
Jul 21 22:28:11 nas node[754314]:                                                                            ^
Jul 21 22:28:11 nas node[754314]: TypeError: Cannot read properties of undefined (reading 'split')
Jul 21 22:28:11 nas node[754314]:     at PlaceClient.getAccessToken (file:///home/place/src/Chief/src/place/PlaceClient.js:115:76)
Jul 21 22:28:11 nas node[754314]:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Jul 21 22:28:11 nas node[754314]:     at async PlaceClient.connect (file:///home/place/src/Chief/src/place/PlaceClient.js:17:29)
```
Not sure what caused it.

**Comment by NoahvdAa** [comment]
This happens when Reddit doesn't return an access token for some reason. This error is now being handled properly without crashing in fb6cc10.
